const dataPresentes = [
  {
    status: "disponivel",
    nome: "Microondas",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Filtro de água",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Aspirador de pó",
    url: "https://www.google.com/search?q=aspirador+de+p%C3%B3+vertical+&sa=X&rlz=1C5CHFA_enBR897BR897&biw=1600&bih=876&tbm=shop&sxsrf=APq-WBsq9GTpaKl_-mfC0LXuRb9vDiIXRA%3A1646909073516&ei=kdYpYta-HpbW1sQP_Oi8uAU&ved=0ahUKEwiWy7ayrrv2AhUWq5UCHXw0D1cQ4dUDCAY&uact=5&oq=aspirador+de+p%C3%B3+vertical+&gs_lcp=Cgtwcm9kdWN0cy1jYxADMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgQIABBDMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6DQgAELEDEIMBELADEEM6BwgAELADEEM6CAgAEIAEELADOgsIrgEQygMQsAMQJ0oECEEYAVDeAlj5DWDpD2gBcAB4AIABjAGIAZMJkgEDMC45mAEAoAEByAEQwAEB&sclient=products-cc",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Chaleira elétrica",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Sanduicheira",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Mixer",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Batedeira",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Liquidificador",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Cafeteira",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Jogo de pratos",
    qtd: 2,
    url: "https://www.camicado.com.br/p/aparelho-de-jantar-lalezar-12-pecas-home-style/-/A-100143720-br.lc?sku=100143738&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMB9XmWCARMuaYuPanvmmBfwtH9GC7gsP8drLzgRak-j_pu203QQKqBoC8LEQAvD_BwE",
  },
  {
    status: "disponivel",
    nome: "Jogo de copos",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Jogo de Talheres",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Jogo de xícaras",
    qtd: 2,
    url: "https://amaro.com/br/pt/c/casa-jardim/cozinha-mesa-posta/canecas-xicaras/50600279_0072/jogo-6-pecas-xicaras-de-cha-de-vidro-com-pires-de-madeira/transparente?CATARGETID=120080460000082842&CADevice=c&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMAeBR0KIGX1MgGqaFFTsR1tG7keah-04XCB2EUlgt_0xTlK7edwajhoC3pEQAvD_BwE",
  },
  {
    status: "disponivel",
    nome: "Garrafa térmica",
    url: "https://www.zoom.com.br/search?q=wood%20fashion%20garrafa%20termica%20branca",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Panela de pressão",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Potes herméticos",
    qtd: 3,
    url: "https://www.zoom.com.br/search?q=potes%20hermeticos%20tampa%20de%20bambu",
  },
  {
    status: "disponivel",
    nome: "Tigelas inox",
    qtd: 2,
    url: "https://www.americanas.com.br/produto/134388557?pfm_carac=voc%C3%AA%20tamb%C3%A9m%20pode%20gostar%20de...&pfm_index=13&pfm_page=product&pfm_pos=item_page.rr1&pfm_type=vit_recommendation&DCSext.recom=RR_item_page.rr1-mars_ClickCP&nm_origem=rec_item_page.rr1-mars_ClickCP&nm_ranking_rec=14&offerId=6104445852131c3c81b76723",
  },
  {
    status: "disponivel",
    nome: "Jogo de facas de corte",
    url: "https://www.tramontinastore.com/jogo-de-facas-tramontina-plenus-com-laminas-em-aco-inox-e-cabos-de-polipropileno-preto-9-pecas_23498048/p?idsku=23498048&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMPRMCCkYkYEqn58y-DAps1VpxGBBMWGA-X8_32n5v70vxP0vleApfhoCP6EQAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Panos de prato",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Escorredor de louça",
    url: "https://www.zoom.com.br/search?q=escorredor%20de%20lou%C3%A7a%20inox",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Balde de gelo",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Tábuas de corte",
    url: "https://www.havan.com.br/jogo-de-3-tabuas-de-corte-finecasa-bambu/p?utm_source=google&utm_medium=cpc&utm_campaign=SHOPPINGUD&gclid=CjwKCAjwiuuRBhBvEiwAFXKaNEkDgEMN2shBitMPGz7MDhxW7FOpfIAR7Fsk0FSmO3ftjotvs01XyxoCTaEQAvD_BwE",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Descascador de batata",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Jogo de panelas",
    qtd: 2,
    url: "https://www.zoom.com.br/panelas/conjunto-de-panelas-tramontina-aco-inox-4-peca-s-brava-65400020?_lc=88&searchterm=jogo%20de%20panela%20inox",
  },
  {
    status: "disponivel",
    nome: "Ralador",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Peneira",
    url: "https://www.zoom.com.br/coador-peneira/kit-3-escorredor-coador-peneira-inox-utensilio-de-cozinha-p?_lc=88&searchterm=escorredor%20de%20inox%20",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Luva termica",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Copo medidor",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Vasilhas de vidro",
    qtd: 3,
    url: "https://www.americanas.com.br/produto/1449869558?pfm_carac=potes-hermeticos-vidro&pfm_page=search&pfm_pos=grid&pfm_type=search_page&offerId=5e3491d11729c3bbf140e868&cor=INCOLOR",
  },
  {
    status: "disponivel",
    nome: "Kit utensilios de cozinha",
    qtd: 2,
    url: "https://www.zoom.com.br/utensilios-cozinha/kit-utensilios-6-pecas-aco-inox-concha-garfo-espatula-colher?_lc=88&searchterm=kit%20utensilios%20de%20cozinha%20inox",
  },
  {
    status: "disponivel",
    nome: "Fruteira",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Kit pia cozinha",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Jogo sobremesa",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Escorredor multiuso",
    url: "https://www.zoom.com.br/escorredor-arroz-massa/escorredor-de-arroz-euro-inox?_lc=88&searchterm=escorredor%20de%20inox%20",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Coador de café",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Forma de gelo",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Pegador de salada",
    url: "https://www.pontofrio.com.br/conjunto-de-pegadores-tramontina-utility-66800103-em-aco-inox-6-pecas-15139554/p/15139554?utm_medium=cpc&utm_source=GP_PLA&IdSku=15139554&idLojista=16&tipoLojista=1P&utm_campaign=utld_smart-shopping&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMApoyQ2s1F-nnvyBLkaVx32r-QmbWt--zquGngqT257LzFTTMyX2iRoCwQ8QAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Tapete",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Jogo americano",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Leiteira",
    url: "https://www.tokstok.com.br/leiteira-500-ml-branco-lua/p?idsku=28419&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMEEkGtrdYrDk-x_PS8_XzJG2V_m6zgEK7XsAe-tQbugGteAeNSK_DRoCV3IQAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Porta talher",
    url: "https://www.americanas.com.br/produto/1355287506?epar=ZOOM&opn=YSMESP&hl=lower&utm_source=zoom&s_term=YYNKZU&utm_campaign=marca%3Aacom%3Bmidia%3Acomparadores%3Bformato%3A00%3Bsubformato%3A00%3Bidcampanha%3Azoom&utm_medium=comparadores&franq=01008c11630743d282b7d8bc0818782d&utm_content=01008c11630743d282b7d8bc0818782d",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Porta copos",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Jogo de taças de vinho",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Kit organizador acrilico",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Porta guardanapo",
    url: "https://www.amazon.com.br/Infinite-Home-Porta-Guardanapo-Bamboo/dp/B091G78HFG/ref=asc_df_B091G78HFG/?tag=googleshopp00-20&linkCode=df0&hvadid=456273449207&hvpos=&hvnetw=g&hvrand=14723315262406800434&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001552&hvtargid=pla-1437910819596&psc=1",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Cuscuzeira",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Saleiro e acucareiro",
    url: "https://www.google.com/search?q=saleiro+e+a%C3%A7ucareiro+bambu&rlz=1C5CHFA_enBR897BR897&sxsrf=APq-WBtmxSVS_gW65hLQ4rwzmrll21CvqA:1646846373145&source=univ&tbm=shop&tbo=u&sa=X&ved=2ahUKEwjbhsjoxLn2AhVkSjABHee9AYMQ1TV6BQgBEP4B&biw=1440&bih=789&dpr=1",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Lixeira de pia",
    url: "https://www.google.com/search?q=lixeira+de+pia+inox&sa=X&rlz=1C5CHFA_enBR897BR897&biw=1440&bih=789&tbm=shop&sxsrf=APq-WBvz-LeJWBcfnLI9F_AZlmzfhPME2A%3A1646853845738&ei=1f4oYreELMHX1sQPlouisAY&ved=0ahUKEwj3wuLT4Ln2AhXBq5UCHZaFCGYQ4dUDCAY&uact=5&oq=lixeira+de+pia+inox&gs_lcp=Cgtwcm9kdWN0cy1jYxADMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDoHCAAQsAMQQzoICAAQgAQQsAM6CwiuARDKAxCwAxAnOgQIABBDSgQIQRgBUJ8JWOwPYLkRaAJwAHgAgAG-AogB8wiSAQcwLjIuMS4ymAEAoAEByAEQwAEB&sclient=products-cc",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Frigideira antiaderente",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Canecas",
    qtd: 3,
    url: "https://artex.com.br/pr/caneca-em-porcelana-loki/MUESTCANLO21BC?gclid=CjwKCAiAvaGRBhBlEiwAiY-yMMtzza5s3SDn5bi3nObBhMaTPmtspOYKW4vRKfQTLPZ4XpMqA4Xa6xoCtAAQAvD_BwE",
  },
  {
    status: "disponivel",
    nome: "Prato de sobremesas",
    url: "https://www.magazineluiza.com.br/conjunto-de-pratos-de-sobremesas-com-6-pecas-215cm-ryo-pink-sand-oxford/p/ggcg7gagj1/ud/coso/?&seller_id=casaferrari&utm_source=google&utm_medium=pla&utm_campaign=&partner_id=65409&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMC_sFFjJ8mzNK9ti2n7s8jNaVuhWZMd4oZmBlslbEmAeQ7WRxQzg4BoCdeQQAvD_BwE&gclsrc=aw.ds",
    qtd: 5,
  },
  {
    status: "disponivel",
    nome: "Medidores",
    url: "https://www.americanas.com.br/produto/2534471190?epar=bp_pl_00_go_ud_pmax_geral&opn=YSMESP&WT.srch=1&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMNjm6Fz-JxH4zaOP6RBQVL-QC8tRf6wcAs58J462B5TunsJENCoR4hoCGTEQAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Colher de sorvete",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Descanso de panelas",
    url: "https://www.magazineluiza.com.br/apoio-para-panela-bamboo-2-pecas-mor/p/dbc3293ddk/ud/decp/?&seller_id=morcasaelazer&utm_source=google&utm_medium=pla&utm_campaign=&partner_id=65409&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMP7FJBYBKkoc3F5srB0pB86ZYlIEIep0wqjRjoVhh1GOsQfCcnP9KRoCBLoQAvD_BwE&gclsrc=aw.ds",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Formas",
    url: "https://www.casasbahia.com.br/conjunto-de-assadeiras-tramontina-brasil-5-pecas-13624782/p/13624782?utm_medium=Cpc&utm_source=GP_PLA&IdSku=13624782&idLojista=10037&tipoLojista=1P&utm_campaign=ud_performance_max&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMBNYrRwqbWbAD3cgp5a_3JzUk5KAKOM437PnMnY5Ngf6SZ5sj771lxoCIksQAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Porta tempero",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Petisqueira",
    url: "https://www.google.com/search?q=petisqueira+de+madeira&rlz=1C5CHFA_enBR897BR897&sxsrf=APq-WBsvIdkBm5yBf1wZx63nbzjyqqIlZQ:1646856435546&source=lnms&tbm=shop&sa=X&ved=2ahUKEwjRidim6rn2AhWQs5UCHdl3C_gQ_AUoAXoECAEQAw&biw=1600&bih=876&dpr=0.9",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Porta frios",
    url: "https://www.amazon.com.br/Porta-Frios-Bambu-Tampa-Acrilico/dp/B091D98KRN/ref=asc_df_B091D98KRN/?tag=googleshopp00-20&linkCode=df0&hvadid=379715601072&hvpos=&hvnetw=g&hvrand=10102766898416334745&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001552&hvtargid=pla-1634732835966&psc=1",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Pratos fundos",
    qtd: 2,
    url: "https://www.amazon.com.br/Acervo-Pratos-Fundos-Panelinha-Noz-Moscada/dp/B07T79LP9R/ref=asc_df_B07T79LP9R/?tag=googleshopp00-20&linkCode=df0&hvadid=379685432325&hvpos=&hvnetw=g&hvrand=5896502567769385023&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1001552&hvtargid=pla-840816253625&psc=1",
  },
  {
    status: "disponivel",
    nome: "Toalha de mesa",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Prato de bolo",
    url: "https://now.westwing.com.br/prato-para-bolo-com-pe-em-bambu-liz-natural-21897.html?simple=DEQ21LYO69180-28997&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMBb7gwvWq27E8iuoH2U6NtR84i4C-zSG3dIyfB96t52IhTI30DX6OxoCI-IQAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Bowls",
    qtd: 2,
    url: "https://www.google.com/search?q=bowls&sa=X&rlz=1C5CHFA_enBR897BR897&biw=1600&bih=876&tbm=shop&sxsrf=APq-WBt-Pnikqp1BUM6dcxdhiXrD9WPjTw%3A1649161472473&ei=ADVMYuObHN2a1sQP_KCEiA8&ved=0ahUKEwjjm_md9fz2AhVdjZUCHXwQAfEQ4dUDCAY&uact=5&oq=bowls&gs_lcp=Cgtwcm9kdWN0cy1jYxADMg0IABCxAxCDARCwAxBDMgcIABCwAxBDMgcIABCwAxBDMgcIABCwAxBDMggIABCABBCwAzIICAAQgAQQsAMyCAgAEIAEELADMggIABCABBCwAzIICAAQgAQQsAMyCAgAEIAEELADMgsIrgEQygMQsAMQJzILCK4BEMoDELADECcyCwiuARDKAxCwAxAnMgsIrgEQygMQsAMQJzILCK4BEMoDELADECcyCwiuARDKAxCwAxAnSgQIQRgBUABYAGCNAmgBcAB4AIABAIgBAJIBAJgBAMgBEMABAQ&sclient=products-cc",
  },
  {
    status: "disponivel",
    nome: "Frigideira",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Funil",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Rodo",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Vassoura",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Pá",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Cabide",
    qtd: 3,
    url: "https://www.zoom.com.br/search?q=cabides%20de%20madeira",
  },
  {
    status: "disponivel",
    nome: "Roupa de cama",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Travesseiros",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Lixeiras",
    url: "https://www.zoom.com.br/search?q=lixeiras%20inox",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Toalhas",
    qtd: 3,
    url: "https://www.zoom.com.br/search?q=toalhas%20brancas",
  },
  {
    status: "disponivel",
    nome: "Kit pia banheiro",
    url: "https://www.tokstok.com.br/kit-bancada-3pcs-salvia-autour/p?idsku=363155&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMKP3EDTRN0A_tC9Y928pRJwvAfee2XKquYdvtcUbdwIAtQF-8bDsXBoCq-8QAvD_BwE",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Tapetes banheiros",
    qtd: 3,
    url: "https://www.riachuelo.com.br/tapete-de-banheiro-retangular-you-look-good-casa-riachuelo-premium-off-white-40x60cm-14036614001_sku?utm_id=16340578473&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMF53u1Tj67B6_Z7RAiwZU_OXYVVBcBSoweTzn9wem0ilZGOj7lo5PRoCwSIQAvD_BwE",
  },
  {
    status: "disponivel",
    nome: "Mop spray",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Baldes",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Panos de chão",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Lixeira cozinha",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Toalhas de rosto",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Tapete para porta",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Paninhos multiuso",
    url: "https://www.lojabuettner.com.br/kit-3-panos-multiuso-para-limpeza-25x25cm-em-microfibra-buettner-cooking/p?idsku=6632&gclid=CjwKCAiAvaGRBhBlEiwAiY-yMF5UPVcwJOgBD24pBSeO0Eet0Tg2mOUaegsG4XlzdHGWQZpw4z-7LBoCRboQAvD_BwE",
    qtd: 10,
  },
  {
    status: "disponivel",
    nome: "Vaso de plantas",
    url: "https://www.riachuelo.com.br/vaso-trama-casa-riachuelo-bege-o10-6x20-7cm-13709372001_sku?gclid=Cj0KCQjwuaiXBhCCARIsAKZLt3mc2zAa2TME0ECpmFONMjfPSOltNG03x0lRKWNsU431WtffaFFuvUgaAmqeEALw_wcB",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Ralador de bambu",
    url: "https://m.camicado.com.br/p/ralador-bambus-home-style/-/A-300038578-br.lc?sku=000000000000038578",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Jogo de lençóis",
    url: "https://m.camicado.com.br/p/jogo-de-lencol-charme-percal-300-fios-queen-4pcs-com-aba-americana-branco/-/A-700642189-br.lc?sku=752171921",
    qtd: 3,
  },
  {
    status: "disponivel",
    nome: "Edredom",
    url: "https://www.americanas.com.br/produto/4176831529?epar=bp_pl_00_go_cmb_pmax_geral&opn=YSMESP&WT.srch=1&offerId=61717e2809c351890d23f793&gclid=Cj0KCQjwuaiXBhCCARIsAKZLt3kr8kniQn9jc_T7CQDCgIZJz5FDt88EDi-0occNtkTLwuTvJlneDAcaAqtYEALw_wcB",
    qtd: 2,
  },
  {
    status: "disponivel",
    nome: "Porta talheres",
    url: "https://www.camicado.com.br/p/porta-talheres-bambus-home-style/-/A-300032990-br.lc?sku=000000000000032990",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Saladeira",
    url: "https://www.camicado.com.br/p/saladeira-bambus-natural-35-litros-home-style/-/A-300038029-br.lc?sku=000000000000038029",
    qtd: 1,
  },
  {
    status: "disponivel",
    nome: "Abajour",
    url: "https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwiUioefza_5AhW16FwKHWIBCi0YABAnGgJjZQ&cit=CkQKCAjw_7KXBhANEjQAGSalHTtxSTSlNom6BOlNfPv2CjZYF_JqGgqEwfLLmb6-gUKzLjTwSstPhQcL64BQWIYVGgKVKPD_BwE&ohost=www.google.com&cid=CAESa-D2lFDzuzwKK0MbOm9RS4eEAcyYREM9wkBr6IV4MO6lfzPMzWa2XQ-tErbLb05idtXabacjxO0acgFghTBIcVfRLrGS3SJJENjzzshwqYGNnNjrcmhOh_bpvscoYsfftA3MZQcpWhQokPOW&sig=AOD64_1SzDKZ1pYpfRM92eIvbHS7oZZHtg&ctype=5&q=&ved=2ahUKEwja8v-eza_5AhWNkZUCHdscD-sQwg8oAHoECGIQTQ&adurl=",
    qtd: 1,
  },
] as Models.Item[];

export default dataPresentes;
